.gitignore
Godeps/Godeps.json
Godeps/Readme
README.md
client.go
client_test.go

Fix the issue with the token containing "bearer bearer" during the request.
I add a proper gitignore and add godep to manage more easily dependency.

Fix double bearer token issue

---

apps.go
spaces.go

Add space information and Orgs information into data payload.
Avoiding doing multiple api call.

Enhancement Apps Data

---

apps_test.go
cf_test.go
client.go
client_test.go
orgs_test.go
services_test.go
spaces_test.go

Clean client code and fix ssl issue https://github.com/cloudfoundry-community/go-cfclient/issues/8

Fix and clean code

---

cf_test.go
client.go
client_test.go

Use info endpoint as source of truth..

Get info endpoint Information

---

client.go

Also renamed DopplerAddress to DopplerEndpoint.

Add real doppler endpoint to Endpoint struct.

---

appevents.go
appevents_test.go
payloads_test.go

I added another method to to filter app events by timestamp and actee

App Events Timestamp and Actee Filter options added

---

client.go
client_test.go
secgroups.go

Adds create, delete, update, get, bind, and unbind for security groups.
Tested locally.

Additional functions for security groups

---

client.go

Support client authentication.

---

orgs.go
orgs_test.go
payloads_test.go

It's possible to have more than 50 orgs, so we need to follow the pages url.
This PR fetch all orgs

List all orgs

---

cf_test.go
client.go
payloads_test.go
tasks.go
tasks_test.go

tested with PWS
also fixes #43

Adding support for v3 tasks. Fixing issue with POST and JSON body.

---

appevents.go
appevents_test.go
payloads_test.go

Follow next page when having more than 50 app events. It also adds support for some more event types.

List all AppEvents

---

apps.go
org_quotas.go
org_quotas_test.go
orgs.go
orgs_test.go
payloads_test.go
services.go
services_test.go
space_quotas.go
space_quotas_test.go
spaces.go
spaces_test.go

* Adds methods to list and retrieve Organization Quota Definitions
* Adds methods to list and retrieve Space Quota Definitions
* Adds method to retrieve Organization Quota
* Adds method to retrieve Organization Summary
* Adds method to retrieve Space Quota
* Adds method to retrieve Space Summary
* Fixes a breaking change when listing Services

Organization and Space Quotas & Summary

---

payloads_test.go
service_instances.go
service_instances_test.go

Add list service instances method.

---

payloads_test.go
service_instances.go
service_instances_test.go

Add missing fields to service instance structs.

Update service instance fields.

---

payloads_test.go
spaces.go
spaces_test.go

Add space roles listing.

---

README.md

Spent 30 minutes trying to figure out the copied example main does not work. Hopefully it will save someone else's time. :)

The example actually does not compile

---

cf_test.go
domains.go
domains_test.go
payloads_test.go

List, create, and delete private domains.

---

domains.go

Fix typo on domains url.

---

domains.go
orgs.go
orgs_test.go
payloads_test.go

I wonder how hard it would be to auto-generate this code from the cf api docs...
cc @cnelson

Org by guid

---

client.go

Added feature to initialize client credentials from existing bearer token. The token could be taken from existing CLI session. It allows the go-cfclient to be used in cf cli plugins. See #33

Adding token-based authentication to client

---

appevents_test.go
apps_test.go
cf_test.go
client_test.go
domains_test.go
org_quotas_test.go
orgs.go
orgs_test.go
payloads_test.go
routes_test.go
secgroups_test.go
service_instances_test.go
services_test.go
space_quotas_test.go
spaces_test.go
stacks_test.go
tasks_test.go

This patch also explicitly sets status codes, since not all posts are expected to return the same code.

Add and remove org managers.

---

orgs.go
orgs_test.go
payloads_test.go

- add associate and remove org auditor (not by username)

add associate and remove org users

---

spaces.go
spaces_test.go

Takes in params to `POST /v2/spaces`
https://apidocs.cloudfoundry.org/252/spaces/creating_a_space.html

Add create space function

---

payloads_test.go
spaces.go
users.go
users_test.go

Also support listing managed spaces (/v2/users/:guid/managed_spaces)
and audited spaces (/v2/users/:guid/audited_spaces)

Add support for listing user spaces (/v2/users/:guid/spaces)

---

payloads_test.go
spaces.go
spaces_test.go

Add associate & remove developer to space by username

---

payloads_test.go
users.go
users_test.go

Add creating and deleting users.

---

payloads_test.go
service_plans.go
service_plans_test.go

[#142518045]
Signed-off-by: Ashish Sehra <ashish.sehra@armakuni.com>

Add support for listing service plans (/v2/service_plans)

---

payloads_test.go
service_bindings.go
service_bindings_test.go

Signed-off-by: Pete Jones <peter.jones@engineerbetter.com>

Add support for listing service bindings (/v2/service_bindings)

---

payloads_test.go
user_provided_service_instances.go
user_provided_service_instances_test.go

Signed-off-by: Pete Jones <peter.jones@engineerbetter.com>

Add support for listing user provided service instances (/v2/user_provided_service_instances)

---

payloads_test.go
spaces.go
spaces_test.go

Hi.
This PR adds function for retrieving particular space.
http://apidocs.cloudfoundry.org/258/spaces/retrieve_a_particular_space.html
```
$ go test -run TestGetSpaceByGuid
....
4 total assertions
PASS
ok  	github.com/cloudfoundry-community/go-cfclient	0.007s
```

Added GetSpaceByGuid func.

---

payloads_test.go
service_keys.go
service_keys_test.go

Additonal functionality for retrieving service keys
- list
- get by name
- get by service instance guid

Service keys

---

error.go

Implements the correct CF error structure

---

orgs.go
orgs_test.go

As described here: https://apidocs.cloudfoundry.org/258/organizations/delete_a_particular_organization.html

Allow to delete orgs recursively

---

payloads_test.go
service_bindings.go
service_bindings_test.go

Return service binding by GUID ([API doc](https://apidocs.cloudfoundry.org/263/service_bindings/retrieve_a_particular_service_binding.html))

Add ServiceBindingByGuid()

---

secgroups.go

This will fix the Issue #68 I submitted.
I removed the omitempty on `Code` and `Type` and programmatically remove if it is not the `icmp` protocol.
Perhaps there is a cleaner fix, but this at least allows us to create/update security groups with the ICMP protocol

Fix ASG ICMP Bug

---

orgs.go
payloads_test.go
users.go
users_test.go

It is possible to list users for spaces by each role type, its helpful to do the same by org roles.

add list org users functions

---

users.go
users_test.go

Missed managed orgs off on last PR. My bad.

add list managed orgs function

---

apps.go
payloads_test.go
service_instances.go
service_instances_test.go

Add timestamps to service instances.

---

service_instances.go
service_instances_test.go

Add API call CreateServiceInstance
Add test for CreateServiceInstance
Tested against a bosh-lite.

Add CreateServiceInstance

---

spaces.go
spaces_test.go

Fix `AllowSSH` type.

---

apps.go
apps_test.go
spaces_test.go

Add `DeleteApp` method.

---

payloads_test.go
service_keys.go
service_keys_test.go

- Add GetServiceKeysByGuid
- Fix getServiceKeyPayload so service instance guid matches in all
fields
- Note that GetServiceKeyByGuid is deprecated

Add GetServiceKeysByGuid

---

payloads_test.go
users.go
users_test.go

Note: for us, this PR depends on https://github.com/cloudfoundry-community/go-cfclient/pull so that we can set privileged credentials when creating the `Client`.

Add GetUserByGUID

---

README.md
apps_test.go
client.go
domains.go
isolationsegments.go
payloads_test.go
service_plan_visibilities.go
tasks.go

Thought I'd just push this PR out there before I make my PR to add the missing "retrieve a user" endpoint.

Fix goreportcard issues

---

client.go

When using client credentials, the transport is an oauth2.Transport, so
we need to check for that.
Edit: this is essentially fixing a panic because the transport was not the expected interface type.

Allow skipping TLS on oauth2.Transport

---

client.go
orgs.go
payloads_test.go
users.go
users_test.go

This is ready to go. It depends on my other PRs. Can probably be merged in after the others pretty easily, but if needed I'll rebase after the others are merged.

[includes my other PRs] Add ListOrgManagers

---

orgs.go
orgs_test.go
payloads_test.go
spaces.go
spaces_test.go

Adds support for ListOrgAuditors(), ListBillingManagers(), ListSpaceAuditors(), and ListSpaceDevelopers()

Role listings

---

client.go

The refactor in #163 failed to do this :-)

Store endpoint in refreshEndpoint().

---

buildpacks.go
buildpacks_test.go
payloads_test.go

I have added func [GetBuildpackByGuid](https://github.com/cloudfoundry-community/go-cfclient/pull/168/files#diff-281d421685ccd9f3a631d34ca3b544b0R81), and test for this func.

add function to get a buildpack by guid

---

orgs.go
orgs_test.go

* I have added func ListOrgUsers, and test for this func.
* This func corresponds to [/v2/organizations/:guid/users](https://apidocs.cloudfoundry.org/262/organizations/list_all_users_for_the_organization.html)

add ListOrgUsers func

---

buildpacks.go
buildpacks_test.go
cf_test.go
client.go
payloads_test.go

Signed-off-by: Ed Payne <epay0@allstate.com>

Add support for creating, updating, and uploading buildpacks

---

Gopkg.lock
app_usage_events.go
app_usage_events_test.go
orgs_test.go
payloads_test.go

Adding a test for ListOrgsByQuery.
Co-authored-by: @jtuchscherer jtuchscherer@gmail.com

Adding the client business logic for the App Usage Events enpoint. 

---

payloads_test.go
secgroups.go
secgroups_test.go
space_quotas.go
space_quotas_test.go
spaces.go
spaces_test.go

also refactored duplicate code

Added ability to associate space managers by username

---

README.md
app_update.go
app_update_test.go
payloads_test.go

Needed feature to update apps. Wrote test. Implemented https://apidocs.cloudfoundry.org/280/apps/updating_an_app.html. Tests pass. Solves issue https://github.com/cloudfoundry-community/go-cfclient/issues/15. Updated README.md to reflect new feature.

Initial AppUpdate and AppUpdateTest commit

---

payloads_test.go
service_bindings.go
service_bindings_test.go
service_instances.go
service_instances_test.go

- delete service instance
- delete service binding
- create service binding

Add missing services API calls

---

orgs.go

* Return all pages of results instead of just the first
* Use existing `fetchSpaces` method for DRYness

Paginate org spaces method.

---

apps.go
apps_test.go
cf_test.go
client.go
info.go
info_test.go
payloads_test.go
routes.go
routes_test.go

Adds various abilities to support pushing a new application.
- UploadAppBits
- GetAppBits
- CreateApp
- GetInfo

Add foundational calls to cf push a new app

---

payloads_test.go
route_mappings.go
route_mappings_test.go

* I add func/test for [/v2/route_mappings](https://apidocs.cloudfoundry.org/1.38.0/#route-mappings--experimental-) endpoint

Added functions to make /v2/route_mappings endpoint available

---

app_update.go
app_update_test.go
space_quotas_test.go
spaces_test.go

* I performed `find . -not -path './vendor/*' -and -name '*.go' | xargs gofmt -w`

 Perform go fmt

---

error.go
service_keys_test.go

Update errors to include detail

---

apps.go
user_provided_service_instances.go
user_provided_service_instances_test.go

Changes:
1. Allow more parameters for CreateApp.
2. Added DeleteUserProvidedService.

Additional CreateApp parameters and DeleteUserProvidedService

---

README.md

Breaks long lines, keeps diff easier to handle and display

Update README.md text alignment

---

apps.go
apps_test.go
service_bindings.go
service_bindings_test.go
service_instances.go
service_instances_test.go

Added a way to update service instances, delete route service bindings and start/stop apps

Add functionality

---

orgs.go
orgs_test.go
spaces.go
spaces_test.go

Add ability to set origin of user to remove

Users origin

---

buildpacks.go
buildpacks_test.go
payloads_test.go

Signed-off-by: Geoff Franks <Geoff.Franks@allstate.com>

Support stack associations with buildpacks in the CF API

---

.gitignore
apps.go

Correct wrong error messages introduced in https://github.com/cloudfoundry-community/go-cfclient/commit/b75ec7d52c9cd9b691cf80da587d076afbed4957

Correct error messages

---

isolationsegments.go
isolationsegments_test.go
payloads_test.go
processes.go
v3packages.go

Refactor paging of v3 api objects to use the same url parsing function.
Also discovered that listing v3 isolation segments was not working properly and added a fix.

Paging refactor

---

processes.go

Prevent requestURL from being a shadow variable

---

README.md

+ for a delighting copy-pasta experience

fix example code to import "fmt"

---

payloads_test.go
stats.go
stats_test.go

Add support for the /v3/processes/<GUID>/stats endpoint

Add the ability to get a process's stats

---

payloads_test.go
resource_match.go
resource_match_test.go

This pull requests support for Resource Match Api

Resource match Api Support

---

README.md
environmentvariablegroups.go
service_instances.go
service_instances_test.go

Unlike the existing update function this new has a strongly typed request body that includes all of the SI update parameters.

Add SI update function

---

info.go
info_test.go

Signed-off-by: Michael Stergianis <mstergianis@vmware.com>
Closes #287

Metadata support now compares versions using semver rules

---

client.go

Signed-off-by: Akash Nayak <akash19nayak@gmail.com>

fix: Prevent panic if cfg.AccessToken is empty

---

payloads_test.go
tasks.go
tasks_test.go

Also update tests so this field is present in one test, absent in the other.
Field looks like it was only introduced in ~3.77.0?

tasks: add Relationships to Task struct

---

client/process.go

Add missing query parameters List-processes

---

.gitignore
Makefile
operation/manifest.go
operation/manifest_test.go
operation/push.go
operation/push_test.go

Previously, this library did not support Docker upload and lacked certain v3 attributes. However, I have now added support for Docker upload and included the necessary additional v3 attributes to simplify app deployment.
[V3 App Manifest](https://v3-apidocs.cloudfoundry.org/version/3.147.0/index.html#the-manifest-schema) 
#351

feat: Added support for Docker upload and included additional v3 attributes to facilitate app deployment.

---

client/organization_quota_test.go
resource/organization_quota.go
resource/process.go
resource/route.go
resource/service_usage.go

fix: https://github.com/cloudfoundry-community/go-cfclient/issues/369

fix: omitempty removed from meaningful nullable attributes

---

client/organization_quota_test.go
resource/organization_quota.go

fix: https://github.com/cloudfoundry-community/go-cfclient/issues/373

feat: added WithOrganization in orgquota

---

Makefile
client/client.go
operation/manifest.go
resource/organization_quota.go
resource/quota.go
resource/space_quota.go

This pull request includes the following changes:
1. Enhancements to the manifest functionality.
2. Resolution of issues related to HTTP check endpoints in the manifest.  #382 
3. Refactoring of space and organization quotas.
4. Resolved panic issues that occur when empty content is passed during the upload process.

Refine manifest capabilities and quota management.

---

resource/route.go

Make port attribute of route nullable

fix: port attribute in route cloudfoundry-community#384

---

operation/manifest.go

Added few missing attributes of manifest spec

fix: add missing manifest attributes

---

operation/manifest.go
operation/manifest_test.go

This PR is raised to address and resolve the issue. [#392](https://github.com/cloudfoundry-community/go-cfclient/issues/392)

Ensure successful unmarshaling of service type in Manifest struct

---

client/role.go
client/role_test.go
resource/role.go

feat: Add role via username and origin

---

client/service_instance_test.go
resource/service_instance.go

fix: Refine service instance update attributes

---

resource/service_credential_binding.go

fix: make name attribute nullable 

---

operation/manifest.go
operation/manifest_test.go
operation/push.go
operation/push_test.go

Allow to set manifest app_instances to 0

---

client/buildpack.go
client/buildpack_test.go

fix: Return jobGuid on buildpack delete

---

resource/buildpack.go

fix: Make stack in buildpack pointer

---

resource/stack.go
testutil/template/stack.json

Added all fields for stack

---

Makefile
go.mod
go.sum

Can now run `make update` to update all dependencies

Add updated dependencies target

---

resource/app.go
resource/types.go
testutil/template/app.json

- based on the API doc: https://v3-apidocs.cloudfoundry.org/version/3.185.0/index.html#the-app-object

feat: add "relationships.current_droplet" to app resource

---

resource/organization_quota.go
resource/quota.go
resource/space_quota.go

Corrects the paid services allowed option to be non-nillable.

Add paid services allowed as non-pointer bool

---

README.md
client/filter.go
client/list_opt.go
client/list_opt_test.go

This adds support for multi-valued timestamp filters with different relational operators to support searching via date ranges.
Fixes issue #446

Fix Issue 446

---

resource/organization.go

Add Organization.Suspended as non-pointer bool

---

client/user.go
resource/user.go

Added user creation via username and origin

---

examples/roles/main.go
resource/user.go

Make username and origin fields for  for user resource as pointer strings

---

operation/push.go

This PR enhances the ```AppPushOperation``` by introducing a configurable option to prevent the app from starting automatically after a push. This gives users finer control over deployment behavior.
- Added a new ```stopped``` boolean field to the ```AppPushOperation``` struct to control whether the app should be started after push.
- Default value of ```stopped``` is ```false``` in ```NewAppPushOperation()```, maintaining the current behavior unless explicitly changed.
- Introduced a new method ```WithNoStart(stopped bool)```, to allow external configuration of the ```stopped``` flag.
- closes #486

feat: support pushing an application without starting it
