client.go, client_test.go
Add on options in order to support insecure SSL, use mostly when using local deployment with custom certificate.
=> Add support for insecure SSL

apps.go, apps_test.go, payloads_test.go
When environment_json contains values of different types.
```
{
....
"entity": {
....
"environment_json": {"string": "string", "int": 1}
}
```
}
We get a err,
```
2015/05/06 11:24:32 Error unmarshaling app json: cannot unmarshal number into Go value of type string
```
As we make the assumtption in the App struct that values are always strings
```
type App struct {
Guid        string            `json:"guid"`
Name        string            `json:"name"`
Environment map[string]string `json:"environment_json"`
SpaceURL    string            `json:"space_url"`
SpaceData   SpaceResource     `json:"space"`
c           *Client
}
```
This PR fixes this.
=> Support different types of vals in environment_json

Godeps/Godeps.json, client.go, client_test.go
This PR uses the oauth2 lib for getting the UAA token.
This comes with the added benefit of support for refresh tokens.
=> oAuth token refresh

apps.go, apps_test.go, cf_test.go, orgs_test.go, payloads_test.go, services_test.go, spaces_test.go
We need to follow next_url if present when geting all apps.
```
cf curl "/v2/apps" | head -n 5
{
"total_results": 346,
"total_pages": 7,
"prev_url": null,
"next_url": "/v2/apps?order-direction=asc&page=2&results-per-page=50",
```
=> Follow next_url in ListApps

client.go
Remove unnecessary fetching of token that goes into the ether.
=> Delete duplicate fetching of getToken in doRequest.

apps.go, apps_test.go, cf_test.go, payloads_test.go
I am currently working from a forked version of the go-cfclient as it was the quickest way to get the new features that I require. These features may be useful to others as well, being part of original repo seems most appropriate.
=> Add support for getting and deleting application instance information

payloads_test.go, secgroups.go, secgroups_test.go, spaces.go, spaces_test.go
I noticed during some manual testing that inline-relations-depth fails to return anything if the response is too large. For example if a security group is bound to ~50 spaces no SpacesData was being populated. I have added a manual check to retrieve spaces data if none was returned dynamically.
As this check largely re-used parts of the ListSpaces function I split it out and re-used what I could.
=> Get ListSpaces to follow NextPage and Improve ListAllSecGroups

secgroups.go
When listing space resources was returning an error, list sec groups would return a partial list early instead of an error.
This was bad.
Also fixed logging of respbody as string not byte array.
Signed-off-by: Jim Conner <jim@secret.org.uk>
=> return error from listsecgroups when listspaceresources returns an error

client.go
Sometimes we want to create a request that `go-cfclient` doesn't support, yet. If we can set body (`io.Reader`), we can do that. This PR adds new function `NewRequestWithBody` that allows construct `*request` with arbitrary body. 
For example, with this function, we can easily create a new request to create organization.
```golang
req := c.client.NewRequestWithBody("POST", "/v2/organizations", bytes.NewReader(body))
res, err := c.client.DoRequest(req)
... 
```
=> Enable to set arbitrary body of request

client.go
Fixing GetToken.
TokenSource was not set.
=> Adding token source to uaa auth

appevents_test.go, apps_test.go, cf_test.go, client.go, client_test.go, orgs.go, orgs_test.go, secgroups_test.go, service_instances_test.go, services_test.go, spaces_test.go
Adding options for User Agent
We should be able now to specify the user agent within the configuration
```golang
c := &Config{
ApiAddress: server.URL,
Token:      "foobar",
UserAgent:  "Test-golang",
}
```
I clean a little string printout :p
=> Able to setup User Agent

apps.go, apps_test.go, payloads_test.go
This PR adds support for the [`stats`](https://apidocs.cloudfoundry.org/251/apps/get_detailed_stats_for_a_started_app.html) endpoint of the Apps API by adding the `AppStats` type  and `GetAppStats` function.
=> Adding ability to query for app status.

apps.go, client.go, orgs.go, services.go, services_test.go, spaces.go
Part of #42. If this pattern of passing a `url.Values` makes sense, I'll apply it to other list methods that take query parameters. We could also pass a string if that's clear. Or, to preserve backwards compatibility, `...string` or `...Option`, so that these methods can still be called with no arguments. WDYT?
=> [WIP] Add query parameters to list services.

client.go
`http.DefaultTransport` gives some handy default proxy settings that can be configured by standard env variables like `NO_PROXY` and `HTTPS_PROXY`. Setting it to a new Transport struct instance does not allow proxies to be injected externally. `TLSClientConfig` can still be assigned to DefaultTransport to allow skipping ssl validation.
Also, the if condition can be squashed by passing `SkipSslValidation` bool straight to `tls.Config` instance
=> Use default transport with additional TLS config

README.md
The repo does not have the `develop` branch any more.
=> Remove statement about develop branch

secgroups.go
Per these docs:
https://apidocs.cloudfoundry.org/252/security_group_running_defaults/return_the_security_groups_used_for_running_apps.html
https://apidocs.cloudfoundry.org/241/security_group_staging_defaults/set_a_security_group_as_a_default_for_staging.html
The status code returned is 200 not 201, I have also tested this behavior with a simple app and have confirmed that CF does indeed return a 200 on a successful request.
=> now using proper status code

Godeps/Godeps.json, appevents.go, apps.go, buildpacks.go, buildpacks_test.go, client.go, client_test.go, domains.go, error.go, org_quotas.go, orgs.go, routes.go, secgroups.go, service_instances.go, services.go, space_quotas.go, spaces.go, stacks.go, tasks.go, tasks_test.go, users.go
This is a work in progress for improving error handling. 
Before these changes, errors from Cloud Foundry would not be correctly parsed or not parsed at all and when such an error occurred, as a library user you were left in the dark. 
I changed pretty much every invocation. It's better now but there is still too less consistency across all API functions.
=> Improve error handling

client.go, client_test.go
This allows callers to specify non-default values in config, e.g. a
non-zero http.Client.Timeout value to support non-blocking API calls.
While this could also be applied to the TLSClientConfig settings, SkipSslValidation
has been kept in cfclient.Config to remain backward-compatible.
This pull request supersedes [PR #81]
=> Reuse config.HttpClient in cfclient.NewClient

orgs.go, spaces.go
I would like to be able to associate and dissociate users from orgs without making a request for an org, so I aliased the relevant methods of `Org` to `Client`. Alternatively, we could add a `Client.NewOrg` method that returns a new `Org` struct without calling the API, like this:
```go
func (c *Client) NewOrg(guid string) {
return Org{Guid: guid, c: c}
}
```
so that I can use `client.NewOrg(orgGUID).AssociateUser(userGUID)`.
WDYT @jcscottiii @lnguyen ?
=> Expose org methods on client.

client.go
If the `config.HttpClient` uses `DefaultTransport` directly then any change to its properties applies to all instances of default `net/http.Client` as well. This PR proposes using a copy of `DefaultTransport` created by dereferencing the pointer so that any TLSClientConfig applies only to the go-cfclient and does not pollute the global namespace.
=> Make HttpClient use a copy of DefaultTransport

appevents_test.go, apps_test.go, buildpacks_test.go, cf_test.go, client_test.go, domains_test.go, isolationsegments.go, isolationsegments_test.go, org_quotas_test.go, orgs_test.go, payloads_test.go, routes_test.go, secgroups_test.go, service_bindings_test.go, service_instances_test.go, service_plans_test.go, services_test.go, space_quotas_test.go, spaces_test.go, stacks_test.go, tasks_test.go, user_provided_service_instances_test.go, users_test.go
Support of PCF Isolation Segments. Added support for testing POST body in the 
test infrastructure (as *string which can be switched later to a more complex 
structure if needed). For that it was required to add the new struct field as nil in 
the existing tests.
Daniel
=> Adding support for isolation segments (PCF 1.10)

client.go, client_test.go
At the moment, we're relying on the `c.config.HttpClient.Do` to always
return a response. It's very odd approach, presuming it will always
success. If it does manage to fail, we'd like to be able to continue
without causing the panic.
With the following change, we're going to gracefully fail, before
continuing with our if statement.
At the end, when all the errors have managed to be omitted, we can
safely return a `nil`.
- Lurking over the code
- Running `ginkgo`/`go test`
=> Fix the DoRequest call on faulty URLs

payloads_test.go, service_plan_visibilities.go, service_plan_visibilities_test.go
Adds [list service plan visibilities](https://apidocs.cloudfoundry.org/258/service_plan_visibilities/list_all_service_plan_visibilities.html) and [create service plan visibility](https://apidocs.cloudfoundry.org/258/service_plan_visibilities/creating_a_service_plan_visibility.html) functionality.
=> Add service plan visibilities functionality

client.go
Unmarshalling into `CloudFoundryErrors` didn't work for me because CF returned only one error.
=> Fix error handling for requests

payloads_test.go, routes.go, routes_test.go
This adds functionality to create a TCP route with a random port
https://apidocs.cloudfoundry.org/258/routes/creating_a_route.html
Signed-off-by: Felix Reyn <freyn@pivotal.io>
=> Add functionality to create TCP route

cf_test.go, domains.go, domains_test.go, payloads_test.go
Found an issue with the way we were handling errors in the private_domains/shared_domains lookup calls.
Signed-off-by: Felix Reyn <freyn@pivotal.io>
=> Fixed errors with get private and shared domain calls

client.go
Use case: I want to use an unsupported authentication method--specifically, I want to use an access and refresh token from the oauth login flow, along with the associated client credentials. Instead of adding yet another authentication method to `NewClient`, I thought it would be easier to make the inner `Config` public so that I can make a client with a custom `Config` without calling `NewClient` at all.
=> Make Client.Config public

apps.go, apps_test.go, service_bindings.go, service_bindings_test.go, service_instances.go, service_instances_test.go, tasks.go, tasks_test.go, user_provided_service_instances.go, user_provided_service_instances_test.go
With aliases for backward compatibility.
=> Use consistent names for get by guid methods.

apps.go, apps_test.go
* move to list apps to function of its own: listApps()
* reuse listApps() for ListAppsByQuery()
* reuse listApps for new function ListAppsByRoute()
* same for unit tests: assertAppList()
=> expose /v2/routes/{uuid}/apps endpoint in ListAppsByRoute()

appevents_test.go, apps.go
Use case: I would like to query the latest 5000 apps and ignore the others in my super big env (50 K apps). The current REST API of CloudController doesn't support limiting the query results. This PR provide this support on client side
=> Provide limits capability for cfclient when querying app info

service_bindings.go
- This iterates through the NextUrl returned from the CF API until all
service bindings are captured.
- Previously only 50 results are returned.
- Heavily referenced ListApps()
=> Expand ListServiceBindings to capture ALL service bindings

orgs.go, orgs_test.go, spaces.go, spaces_test.go
Since query parameters to `DeleteOrg` are positional arguments, adding the recommended `async` flag winds up as a breaking change. I'm happy to revert if we're trying to avoid breaking changes. We could also allow delete methods to accept a `url.Values`.
=> Add delete space method.

domains.go, isolationsegments.go, secgroups.go, service_plan_visibilities.go
This patch removes the byte casting for raw bodies
during unmarshal since they are already byte arrays
due to ReadAll usage.
Signed-off-by: Marcela Bonell <marcelabonell@gmail.com>
=> Remove unnecessary conversions

cf_test.go, payloads_test.go
This patch removes unused code from unit tests, one
constant and one type were removed.
Signed-off-by: Marcela Bonell <marcelabonell@gmail.com>
=> Remove unused const and type in unit test

service_instances.go
Add "Parameters" and "Tags" to the ServiceInstanceRequest struct to allow providing parameters and tags to the service instance creation request.
=> Add support for service instance creation with parameters and/or tags

payloads_test.go, service_brokers.go, service_brokers_test.go, service_instances.go, service_plans.go, services.go, services_test.go
This commit adds:
1.  support in the library for the [service broker management APIs](https://apidocs.cloudfoundry.org/272/#service-brokers).
2.  fixes a bug in ListServicesByQuery and ListServicePlansByQuery where only the first page of results would be returned instead of all of the results.
3. adds GetServiceByGuid
=> Add support for Service Broker management APIs

buildpacks.go, buildpacks_test.go
Similar to
https://github.com/cloudfoundry-community/go-cfclient/pull/125
It would be nice to have timestamps for buildpacks in order to compare
based on the timestamps
=> Add timestamps to buildpacks

cf_test.go, client.go, client_test.go
When using username/password authentication the Client fetches a token on creation to be used as the token source. This token expires eventually and is only refreshable by creating a new Client object.
Capture the expiration of the token and refresh the oauth client when it expires.
fixes #34
updates cloudfoundry-community/stackdriver-tools#177
=> Respect expiration of password token source

spaces.go
Without the "omitempty" parts, the GO marsheller adds "nil" entries to the request for all the arrays in the request structure. Cloud Foundry fails to create the space with an  error:
cfclient: error (1002): CF-InvalidRelation
This error is fixed by adding "omitempty" to the non-required parts of the request.
=> Added "omitempty" for optional parameters

apps.go, apps_test.go
Adding a new function call `GetAppByGuidNoInlineCall` which allow to get app, org, space information without the need of `inline-relations-depth=2` which is deprecated and could lead to issue on big env.
=> Getting Apps without IRD=2 call

events.go, events_test.go
Hi, 
I was using your library to get a list events, but I found out that the library didn't expose the time each of these events was created. That timestamp is really relevant for auditing to know when something happened.
Please, let me know if you need further changes.
=> Add CreatedAt to event resource

.travis.yml, client.go, client_test.go
This has caused us multiple hours of headaches where the cloud controller would not honor the query params if there was a double slash in the URL. 
Note: this does not happen against every CF environment, it appears to depend on the load balancer before the routers.
To avoid that, we just remove the trailing slash of the API Address.
Co-authored-by: Adham Abdelwahab <ahelal@users.noreply.github.com>
=> Removing trailing slashes from the API Address

domains.go, org_quotas.go, org_quotas_test.go, orgs.go, orgs_test.go, payloads_test.go, secgroups.go, secgroups_test.go, space_quotas.go, space_quotas_test.go, spaces.go, spaces_test.go
Sorry in advance for such a large PR, but added features I needed to have to replace existing approach for interacting with cloud controller.
- associate space managers by username
- update space
- update org
- list security groups for a space
- unbind running and staging security groups
- create/update space quotas
- adding support to associate quota with a space
- create/update org quotas
- list org private domains
- add/remove org billing managers
- share/unshare existing org private domain with other orgs
- adding isolation_segment_guid to returned space struct
=> Adding additional API features

isolationsegments.go, isolationsegments_test.go
When creating an isolation segment to org relationship the API returns an http status code `200` on success as [documented](http://v3-apidocs.cloudfoundry.org/version/3.44.0/index.html#entitle-organizations-for-an-isolation-segment) and not a `201`.
=> Fix the expected http status code when calling iso segment AddOrg

orgs.go
Org status is returned when listing or getting an org. This PR allows the status to be accessed.
=> Add missing status field to Org

Gopkg.lock, Gopkg.toml, secgroups.go, secgroups_test.go
This method will return an error for API versions before `2.68.0`.
=> Add BindSpaceStagingSecGroup method

cf_test.go, isolationsegments.go, isolationsegments_test.go, orgs.go, orgs_test.go, spaces.go, spaces_test.go
Per v3 docs
http://v3-apidocs.cloudfoundry.org/version/3.50.0/#assign-default-isolation-segment
http://v3-apidocs.cloudfoundry.org/version/3.50.0/#manage-isolation-segment
=> Adding ability to "patch" org/space with isolation segment guid

service_instances.go, service_instances_test.go
The correct query param the broker expects is accepts_incomplete rather
than async
=> Fix query param on DeleteServiceInstance

orgs.go, orgs_test.go, spaces.go, spaces_test.go
If you have users with the same username but different origin (uaa,ldap,saml) then you need to specify the origin when adding/removing from org/space roles otherwise will get the following error if 2 users exist with same user name but different origin `cfclient: error (20006): CF-UserIsInMultipleOrigins`
=> Added ability to specify origin when adding/remove users from roles

payloads_test.go, service_bindings.go, service_bindings_test.go, service_keys.go, service_keys_test.go
Hello!
@abg and I are working on a utility that uses this package, and noticed that the ListServiceKeysByQuery function didn't have page support, so we added that in in this PR. We also cleaned up the implementation of ListServiceBindingsByQuery to remove the unnecessary `page` counting, and added test coverage for these two functions' paging feature.
Let us know if there's anything else we can do to help make this shippable!
=> Support searching multiple pages when listing service keys, bindings

apps.go
When creating a **Non-Docker** app with this library a `docker_credentials` block is added to the JSON request. This is due to the actual `username` and `password` not containing the `omitempty` flag. 
This PR fixes the issue allowing users to use AppCreateRequests for non-docker use cases.
=> remove username/password when cf app is not a docker image

client.go, error.go, payloads_test.go, tasks_test.go
CloudFoundry APIs in V3 returns a different model than V2.
Currently this library only handle the V2 model (see #108) and fails if the V3 model is returned from the API.
This PR is related to https://github.com/cloudfoundry-community/go-cfclient/issues/203
\cc @dbu
=> Handle and convert errors from APIs V3 into V2 model

apps.go, apps_test.go, payloads_test.go
* currently the only way to get an AppSummary struct is via space.Summary()
which isn't always the nicest
* AppSummary has occaisionally useful information, such as RunningInstances
which is unique to AppSummary
* I'd like to use this to find apps where RunningInstances < Instances
(eg, apps having "issues")
=> Add App.Summary() func

client_interface.go
Two private methods accidentally snuck into the interface definition, wreaking havoc on non-package implementations.
Signed-off-by: Mike Lloyd <mike.lloyd@gsa.gov>
=> removed two very sneaky non-exported private methods.

events.go, events_test.go, payloads_test.go
Our `Event` type represents items from [Cloud Controller's `/v2/events` endpoint](https://apidocs.cloudfoundry.org/10.1.0/events/list_all_events.html). There is a `metadata` field missing from our `Event` type. This field is important because it gives more context on what each event did. This PR adds that missing field.
I used `map[string]interface{}` because the values can have varying types. This is [what the CF CLI did](https://github.com/cloudfoundry/cli/blob/c830f550c33a44283780f90f7854e5ed16431d2f/cf/api/resources/events.go#L25).
The test had to workaround that neither `ShouldEqual` or `ShouldResemble` correctly compared that type.
=> Add missing `metadata` field to Event

.travis.yml
We're running on newer Go versions in CI now, so we need to invoke
go vet directly (with a list of packages) rather than running
go tool vet (with a list of files).
=> Fix CI: invoke go vet directly

payloads_test.go, v3droplet.go, v3droplet_test.go
This includes a rename of the response for setting an app's current droplet, as the response is shared between the GET/SET calls.  While this rename is a breaking change, it's unlikely to impact anyone who is not actively working with the new code since the existing V3 call was only merged a few days ago.
Closes #259
=> Add v3 call to get an app's current droplet

payloads_test.go, v3droplet.go, v3droplet_test.go
Using `/v3/apps/:guid/droplets/current` gives inline information that has to be fetched in a secondary call when using `/v3/apps/:guid/relationships/current_droplet`.
=> Use a different call to get v3 app's current droplet

client.go
Added support for login in with an "origin" option.
Documented at https://docs.cloudfoundry.org/api/uaa/version/74.0.0/index.html#password-grant .
If the Cloud Foundry UAA has multiple identity providers configured, this allows login
in with a specific identity provider.
=> Support the "origin" option for password login

payloads_test.go, v3organizations.go, v3organizations_test.go
Since I need to be able to get annotations and labels of organizations for a project of mine, I implemented the v3 organizations endpoint.
I did run some basic tests in my sandbox environment but I would appreciate if someone else would review/test it additionally.
Since booleans are kind of difficult to handle in conjunction with `omitempty` and string values don't seem to be accepted by the API, I've used a pointer of type bool for the `suspended` parameter.
That way I am able to check whether it was provided in the request or not.
Please let me know in case something is missing or should be implemented differently.
=> Add basic implementation for v3 organizations

README.md, apps.go, orgs.go, spaces.go, users.go, v3apps.go, v3organizations.go, v3packages.go, v3spaces.go
This adds basic paging support to all v3 ListByQuery functions and the major v2 ListByQuery functions and generally fixes #223 
This implementation is completely backwards compatible and introduces very few code changes. This should allow consumers of this library to implement better feedback/control on foundations with large result sets.
There are a couple of downsides to this implementation that can't easily be addressed without returning a higher level page result/request object:
1. The request params are completely non-typed as url.Values.
2. The calling code has to implicitly break when it encounters a len(result slice) < page size because we don't return any pagination meta data. This means that if you have 100 items and your page size if 50 you will have to make 3 calls to the API …
=> Add paging support to ListByQuery functions

appevents.go, apps.go, buildpacks.go, cf_test.go, client.go, client_test.go, domains.go, isolationsegments.go, org_quotas.go, orgs.go, payloads_test.go, resource_match.go, secgroups.go, service_brokers.go, service_plan_visibilities.go, service_plans.go, services.go, space_quotas.go, stacks.go, tasks.go, user_provided_service_instances.go, v3apps.go
Applies many non-breaking, low hanging fruit linting suggestions of the golangci-lint tool.
- Remove superfluous comments on exported consts
- Correct spacing before comment start
- Replace magic-number status codes with net/http constants
- Close request response bodies
- Reduce variable scope to within if initializer
- Correct typo in log message
- Remove unused struct code
- Remove unused constant from payloads_test.go
- Panic on time.Parse() error instead of returning nil silently
- Prefer increment operator over +=1 syntax
- Prefer switch statements over if-elseif chains
- Correct capitalization of URL in non-exported usages
=> apply golangci lints

domains.go, domains_test.go
Fixed a bug in ``GetDomainByGuid()`` and ``GetSharedDomainByGuid()``: The ``CreatedAt`` and ``UpdatedAt`` field was not merged and thus always empty.
=> Bugfix: Set CreatedAt and UpdatedAt in Get(Shared)DomainByGuid

payloads_test.go, v3roles.go, v3roles_test.go, v3security_groups.go, v3security_groups_test.go, v3spaces.go, v3spaces_test.go, v3stacks.go, v3stacks_test.go, v3types.go, v3users.go
We are migrating our software to use v3 API and discovered that cfclient was missing some methods that we needed, so we decided to implement them. We have implemented only the ones that we use so the list of methods is still not complete. 
- read the code and run `make test`
- share your thoughts :)
=> Implement some missing v3 functions

payloads_test.go, service_instances.go, spaces.go, spaces_test.go
The v2 spaces api has a GET resource for retrieving all service instances
for a space that may behave more consistently than the v2 services instances
api that can be called with a space guid.
=> Add support for listing service instances in a space

payloads_test.go, v3service_credential_bindings.go, v3service_credential_bindings_test.go
The v2 api only supports 2 query parameters for service key : name and service_instance_guid. The endpoint becomes service_credential_bindings in v3 and supports more query parameters.
=> Add support for listing service credential bindings

v3routes.go
The V3Route struct was missing the destination array, as described in #317
The routes object does contain a destination array linking target apps of domains, would be good to also have this accessible through the struct.
https://v3-apidocs.cloudfoundry.org/version/3.126.0/index.html#the-route-object
=> Add destinations to V3 Routes Struct

client.go
The current implementation fails to close the response body when encountering an error while reading it.
=> Fix resource leak when reading the response body

client/process.go, client/process_test.go
I hope the process section of the client is the correct place to put this. Otherwise we may add a file for stats or put this into the app section.
GET /v3/apps/:guid/processes/:type/stats
[V3 API](https://v3-apidocs.cloudfoundry.org/version/3.143.0/index.html#get-stats-for-a-process)
#343
=> Process Stats by App GUID

config/config.go, config/config_test.go, config/options.go, internal/http/client.go
In this Pull Request, I've implemented enhancements to address a specific limitation: 
1. While the user password grant type previously supported only the default client (cf), it now accommodates the use of alternative clients, which was not possible before. Now we can achieve like below
```go
config.New("https://api.cf.com", config.ClientCredentials('test', 'test'), config.UserPassword('test', 'test'))
```
2. At present, duplication of the client request body occurs when utilizing `bytes.Buffer`, `bytes.Reader`, and `strings.Reader`.
3. Reattempt the client request following the expiration of the refresh token.
4. Eliminate the use of loops in implementing retry logic.
=> Enhance multiple auth support and auth client

client/security_group_test.go, resource/security_group.go, testutil/pointer.go
Globally enabled running and staging flags should be optional for security groups allowing only the security group name or rule definitions to be updated.
=> Add fix for issue #378

client/service_credential_binding.go, client/service_credential_binding_test.go
=> fix: Delete Service Credential Binding does not return job GUID 

resource/service_credential_binding.go
=> fix: Added omitempty for binding detail attributes

client/process_test.go, resource/process.go, testutil/template/process.json
- Add new readiness process health check
- Add missing interval to old health check
=> Add CF app readiness checks

client/app_test.go, client/revision_test.go, resource/app.go, testutil/object_generator.go, testutil/template/app_environment_expected.json, testutil/template/app_envvar.json
Currently the go-cfclient throws an error when attempting to retrieve env vars for an app that are not of type string. 
For example, given the env vars:
```
○ → cf curl /v3/apps/a275abd1-8f53-4a63-b980-d81cee1cf133/environment_variables
{
"var": {
"SCS_CREDHUB_ENABLED": true,
"JBP_CONFIG_OPEN_JDK_JRE": "{jre: {version: 17.+}}",
...
},
"links": {
"self": {
"href": "https://< sanitized >/v3/apps/a275abd1-8f53-4a63-b980-d81cee1cf133/environment_variables"
},
"app": {
"href": "https://< sanitized >/v3/apps/a275abd1-8f53-4a63-b980-d81cee1cf133"
}
}
}
```
We observe the following failure:
time=2024-07-15T20:43:48.368890666Z caller=logger.go:73 level=error error="failed to get environment for app a275abd1-8f53-4a63-b980-d81cee1cf133: error decoding …
=> Support parsing of environment variables other than strings.

resource/process.go
These 2 fields were added some time ago, but were not yet present in the go-cfclient library.
=> add ProcessStat fields cpu_entitlement and log_rate

internal/http/client.go
The request context has set up a deadline of value DefaultRequestTimeout. The function CreateOAuth2TokenSource would store that context in the token source creator. The token source creator would later try to create a new Token(), but fail since the deadline would be reached.
The context passed to oauth2 package controls which HTTP client is used. See the oauth2.HTTPClient variable.
Therefore fix the situation by passing an empty context to oauth2 package.
Fixes #444
=> Fix: Provide empty context without deadline

Makefile
Assume golangci-lint is installed into the bin directory by the installer script.
=> Add corrected golangci-lint path to match installer

client/build.go, client/job.go, client/job_test.go, client/package.go, client/polling.go, client/polling_test.go, operation/push.go, testutil/object_generator.go, testutil/template/job_failed.json
Fixes #437 and adds to PR #438.
Error and warning details are now returned as part of the polling function. This allows consumers to know why an operation entered the FAILED state without needing to re-query the CF API.
=> Verbose error polling

client/build_test.go, client/droplet_test.go, resource/app.go, resource/build.go, resource/droplet.go
Add optional image update to builds for consistency with droplets and remove unnecessary pointer from droplet image field.
=> Build update image

resource/organization.go
Display all parameters of org usage_summary endpoint as described in CF v3 API documentation - https://v3-apidocs.cloudfoundry.org/version/3.190.0/index.html#get-usage-summary
=> add usage summary parameters

README.md, config/config.go, config/config_test.go, config/options.go, examples/auth/main.go, internal/jwt/token.go, internal/jwt/token_test.go
This PR brings in support for authentication:-
- Using JWT Bearer token instead of user/password clientid/client-secret flow
- Using Client Assertion Token instead of client Secret
This is primarly used with the new JWT Bearer
- Based on RFC-7523
- Feature is supported from UAA 76.23.0 & cf-cli v8.12.0
fixes: #474
=> feat: Support assertion based auth

CHANGELOG.md, README.md, client/app_test.go, client/build_test.go, operation/push.go, resource/app.go
I want to add support for using the CNB lifecycle when pushing apps using the Terraform provider, which uses this CF client library. I thought it would be best to first have CNB lifecycle support exist here in the client that the Terraform provider uses.
Confession time 🥺👉👈 : I am not a good Go programmer, but GitHub Copilot claims to be. I don't personally see any problems with the code it generated, but not being an expert in Go code, tooling, and testing facilities, it's possible and even likely that I missed something. Please let me know if you see problems or want changes!
=> Add support for setting app lifecycle

operation/push.go, operation/push_test.go
The Docker lifecycle requires that data be set, even if it's empty. I set Claude Sonnet V4 loose on it. After some guidance, here's what you're seeing:
---
Summary
I successfully fixed the issue in the go-cfclient library that was preventing docker lifecycle apps from being created. Here's what was accomplished:
✅ Problem Identified
The docker lifecycle was failing with "Lifecycle data must be an object" because the build creation was setting only the `Type` field without the required `Data` field in the lifecycle structure.
✅ Root Cause Fixed
Modified `push.go` in the buildDroplet method to provide an empty DockerLifecycle{} struct as the `Data` field for docker lifecycle builds.
✅ Comprehensive Testing
All lifecycle types now work correctly:
-  Buildpack lifecycle: Creates traditional …
=> Fix Docker lifecycle creation issue

operation/manifest.go, operation/manifest_test.go, operation/push.go, operation/push_test.go
(It's me again, @sneal, sorry.)
I missed adding "lifecycle" attribute support in the manifest processing. Without this the Terraform provider (and probably other consumers of this) have to do a lot more work to get an app with an explicit lifecycle to work. 
If you're willing to merge this and tag a `-alpha.15` I would be ever so grateful!
=> Add lifecycle to manifest
